### ISSUE TITLE
pre-population of mongodb

### ISSUE THREAD

**Issue by gugakatsi** [katgironpe/sinatra-mongodb-grape#4]
newbie here,  i am interested with what would be "best" approach to pre-populate mongodb in this scenarion , as well i am gonna use it as rest api , i already have some data i wanna upload so , if you help me i would  be happy  . thanks in advance.

**Comment by katgironpe** [comment]
@gugakatsi Just create a rake task that will pre-populate the database. You have to specific about any issues you encounter.

**Comment by gugakatsi** [comment]
@katgironpe i already solved issue but huge thanks for answer anyways.
